---
- name: Install libnss-mysql
  yum:
    name="libnss-mysql"
    state="present"

- name: Enable siteworx multiple ssh feature
  command: >
    /home/interworx/bin/config.pex
    --global
    --set
    --name SITEWORX_SSH_FEATURE
    --value on
