---

- name: Enable Interworx SCL PHP Support
  command: >
    nodeworx
    -unv
    -c Http
    -a enableMultiplePhp

- name: Find Installed PHP Versions
  shell: >
    find "{{ php_remi_root }}" -maxdepth 1 -name 'php*' -printf '%p,' | sed 's/.$//'
  register: directory_php_names

- name: Enable Installed PHP Versions
  command: >
    nodeworx
    -unv
    -c Http
    -a multiplePhpOptions
    --enabled_php_versions "{{ directory_php_names.stdout }}"

- name: Find Latest PHP Version
  shell: >
    ls -1r --sort version "{{ php_remi_root }}" | awk 'NR==1{ print $1 }'
  register: latest_php_version

- name: Set Default PHP Version to Latest
  command: >
    nodeworx
    -unv
    -c Http
    -a multiplePhpOptions
    --default_php_version "{{ php_remi_root }}/{{ latest_php_version.stdout }}"
